# FRF Tekton Pipeline: v18.0.1
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: "pr-{{pull_request_number}}.frf-cloud-run-pipelinerun-prod"
  labels:
    tekton-notify.iac.ford.com/name: "pr-{{pull_request_number}}.frf-cloud-run-pipelinerun-prod"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && (target_branch == "main" ||
                          target_branch == "refs/heads/main")
    pipelinesascode.tekton.dev/max-keep-runs: "2"

    tekton-notify.iac.ford.com/generate-from-annotations: "true"
    tekton-notify.iac.ford.com/git-enabled: "true"
    tekton-notify.iac.ford.com/git-use-pac-secret: "true"

    # *** REPLACE THE SQUARE BRACKET VALUE BELOW WITH YOUR OWN PROJECT BUCKET NAME ***
    tekton-notify.iac.ford.com/gcs-bucket-name: "[PROJECT-BUCKET-NAME]"
    tekton-notify.iac.ford.com/gcs-bucket-path: logs/{{target_namespace}}/{{repo_name}}/{{source_branch}}
    tekton-notify.iac.ford.com/gcs-bucket-wif-gcp-sa: "[GCP-PIPELINE-SERVICE-ACCOUNT]"
    tekton-notify.iac.ford.com/git-remove-pr-commits: "false"
    tekton-notify.iac.ford.com/git-remove-pr-comments: "true"
    tekton-notify.iac.ford.com/git-comment-heading: "{TN_PIPELINE_NAME_UPPER}"

    # *** UNCOMMENT THE LINE BELOW IF YOUR REPO IS IN GHEC (github.com) ***
    tekton-notify.iac.ford.com/git-api-url: "https://api.github.com/"

spec:
  params:
    - name: git-repo-url
      value: "{{ repo_url }}"
    - name: git-revision
      value: "{{ revision }}"
    - name: git-target-branch
      value: "{{ target_branch }}"
    - name: git-source-branch
      value: "{{ source_branch }}"
    - name: fossa-config
      value:
        enabled: "true"
        projectName: "votacionbc"
        teamName: ""
        policyName: "Website/Hosted Service Use"
        secretName: "[FOSSA-SECRET-NAME]"
        enableBreakBuildOnIssue: "true"
    - name: sonarqube-config
      value:
        enabled: "true"
        enableBranchAnalysis: "false"
        enableBreakBuildOnIssue: "true"
        enableDebug: "false"
        secretName: "[SONARQUBE-SECRET-NAME]"
    - name: compodoc-enabled
      value: "false"
    - name: buildah-config
      value:
        pipelineServiceAccount: "[GCP-PIPELINE-SERVICE-ACCOUNT]"
        buildExtraArgs: "[BUILDAH-BUILD-EXTRA-ARGS]"
        pushExtraArgs: "[BUILDAH-PUSH-EXTRA-ARGS]"
    - name: cloud-run-config
      value:
        enabled: "false"
        secretName: "[GCP-WIF-ACCOUNT-SECRET-NAME]"
        serviceName: "[DEPLOYED-SERVICE-NAME]"
        projectId: ""
        region: "[GCP-REGION]"
        serviceAccount: "[CLOUDRUN-IDENTITY-SERVICE-ACCOUNT]"
        ingress: "[GCP-INGRESS]"
        vpcEgress: "[GCP-VPC-EGRESS]"
        vpcConnector: "[GCP-VPC-CONNECTOR]"
        imageRegistry: "[GCP-REGION]-docker.pkg.dev"
        imagePath: "/[CONTAINER-IMAGES-FOLDER]"
        imageTag: "[VERSION]"
        additionalFlags: ""
    - name: dynatrace-config
      value:
        dynatraceEnabled: "false"
        dynatraceConnectionPoint: "[DYNATRACE-CONNECTION-POINT]"
        dynatraceClusterID: "[DYNATRACE-CLUSTER-ID]"
        dynatraceTenantID: "[DYNATRACE-TENANT-ID]"
        dynatraceTenantTokenSecretName: "[DYNATRACE-TENANT-TOKEN-SECRET-NAME]"
        dynatraceNetworkZone: "[YOUR-DYNATRACE-NETWORK-ZONE]"
    - name: startup-probe-config
      value:
        initialDelaySeconds: "1"
        failureThreshold: "5"
        timeoutSeconds: "1"
        periodSeconds: "1"
    - name: liveness-probe-config
      value:
        initialDelaySeconds: "30"
        failureThreshold: "3"
        timeoutSeconds: "1"
        periodSeconds: "15"
    - name: jfrog-config
      value:
        authSecret: "[JFROG-AUTHENTICATION-SECRET-NAME]"
    - name: unshallow-clone-enabled
      value: "false"
    - name: build-config-environment
      value: "prod"
  pipelineRef:
    resolver: http
    params:
      - name: url
        # yamllint disable-line rule:line-length
        value: "https://raw.githubusercontent.com/ford-innersource/devenablement.wame.frf-tekton-pipelines/refs/heads/main/pipeline/frf-cloud-run/18.0.1/frf-cloud-run.yaml"
      - name: http-username
        value: "git"
      - name: http-password-secret
        value: "github-https-ghec"
      - name: http-password-secret-key
        value: "token"
  taskRunTemplate:
    serviceAccountName: pipeline
    podTemplate:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
  taskRunSpecs:
    - pipelineTaskName: buildah-ford
      podTemplate:
        securityContext:
          runAsUser: 0
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Filesystem
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    # *** OPTIONAL: Only needed when Dynatrace integration is enabled ***
    # Registry secrets are used by buildah to pull from private Dynatrace registry
    # To enable Dynatrace, uncomment the following workspace bindings:
    # - name: registry-secrets
    #   secret:
    #     secretName: "[FCR-QUAY-ROBOT-SECRET-NAME]"
    # - name: dynatrace-secret
    #   secret:
    #     secretName: "[DYNATRACE-TENANT-TOKEN-SECRET-NAME]"
